import Config

# Configure your database
config :coin_tracker, CoinTracker.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "coin_tracker_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :coin_tracker, CoinTrackerWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:coin_tracker, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:coin_tracker, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :coin_tracker, CoinTrackerWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/coin_tracker_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :coin_tracker, dev_routes: true

# Development log format — includes key metadata for filtering.
# IEx tips (run with `iex -S mix phx.server`):
#   Logger.configure(level: :error)  — silence everything except errors
#   Logger.configure(level: :debug)  — back to normal
#   Logger.remove_handler_filter(:default, :suppress_ecto_debug)  — see SQL queries
config :logger, :default_formatter,
  format: "[$level] $metadata$message\n",
  metadata: [:module, :operation, :symbol]

# Suppress noisy Ecto SQL debug logs in development.
# Remove at runtime: Logger.remove_handler_filter(:default, :suppress_ecto_debug)
config :logger, :default_handler,
  filters: [
    suppress_ecto_debug: {&CoinTracker.DevLogFilter.filter/2, :suppress_ecto_debug}
  ]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# API Client Configuration for CoinScanX
config :coin_tracker, CoinTracker.Signals.CoinscanApiClient,
  base_url: "https://api.coinscanx.com",
  api_key: System.get_env("COINSCANX_API_KEY")

# CoinGecko market-data client (anonymous endpoint; API key wiring is in place
# but unused — set COINGECKO_API_KEY to enable the demo header)
config :coin_tracker, CoinTracker.Signals.CoinGeckoApiClient,
  base_url: "https://api.coingecko.com/api/v3",
  api_key: System.get_env("COINGECKO_API_KEY")

# Telegram ExGram
config :ex_gram, token: System.get_env("TELEGRAM_BOT_TOKEN")
config :coin_tracker, :telegram_bot_username, "coin_tracker_dev_bot"

# Signals Poller Configuration
# Disabled in dev to avoid inconsistent fake API data
# Use one-time ingestion at startup instead (see application.ex)
config :coin_tracker, CoinTracker.Signals.Poller,
  enabled: true,
  interval: :timer.seconds(45)

# Snapshot Poller Configuration
# Reactive: snapshots fire on Poller fingerprint changes, no interval.
config :coin_tracker, CoinTracker.Signals.SnapshotPoller, enabled: true

# Market Status Poller Configuration
# Reactive: captures fire on Poller fingerprint changes, no interval.
config :coin_tracker, CoinTracker.Signals.MarketStatusPoller, enabled: true

# CoinGecko Poller — own 15-minute timer (independent of Signals.Poller).
config :coin_tracker, CoinTracker.Signals.CoinGeckoPoller,
  enabled: true,
  interval: :timer.minutes(15)

# Price Poller Configuration
# Enabled in dev with 5 second interval for real-time price updates
config :coin_tracker, CoinTracker.Coins.PricePoller,
  enabled: true,
  interval: :timer.seconds(5)
