import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :coin_tracker, CoinTrackerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [ip: {0, 0, 0, 0}, port: 8080]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Use JSON formatting for structured logging in production (Grafana/Loki compatible)
config :logger, :default_handler,
  formatter:
    {LoggerJSON.Formatters.Basic,
     metadata: [
       :request_id,
       :error_type,
       :severity,
       :module,
       :operation,
       :exchange,
       :symbol,
       :position_id,
       :user_id,
       :reason,
       :token_prefix,
       :alert_type
     ]}

# Signals Poller Configuration
# Enable polling in production with 5 minute interval
config :coin_tracker, CoinTracker.Signals.Poller,
  enabled: true,
  interval: :timer.seconds(45)

# Snapshot Poller Configuration
# Reactive: snapshots fire on Poller fingerprint changes, no interval.
config :coin_tracker, CoinTracker.Signals.SnapshotPoller, enabled: true

# Market Status Poller Configuration
# Reactive: captures fire on Poller fingerprint changes, no interval.
config :coin_tracker, CoinTracker.Signals.MarketStatusPoller, enabled: true

# Price Poller Configuration
# Enable polling in production with 5 second interval for real-time price updates
config :coin_tracker, CoinTracker.Coins.PricePoller,
  enabled: true,
  interval: :timer.seconds(5)

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
